#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: WellArt

# Short bio or description (displayed in the header)
description: My lorem ipsum

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/wellart/wellart.github.io/master/images/avatar.jpg
#theme: jekyll-theme-hacker
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
